name: Publish to npm

on:
    push:
        branches:
            - 'develop'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: '14'
            - run: npm lint
            - run: npm build
            - uses: JS-DevTools/npm-publish@v3
              with:
                  token: ${{ secrets.NPM_TOKEN }}
